//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyzerTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalyzerTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;&lt;html class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        /// &lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Ireland MCLDirect | Contact Us&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Fast delivery from MCLDirect.com Newbridge Ireland&quot; /&gt;
        ///    &lt;meta  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MCLDirect {
            get {
                return ResourceManager.GetString("MCLDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE HTML&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head id=&quot;Head1&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///            (function () {
        ///                var _fbq = window._fbq || (window._fbq = []);
        ///                if (!_fbq.loaded) {
        ///                    var fbds = document.createElement(&apos;script&apos;);
        ///                    fbds.async = true;
        ///                    fbds.src = &apos;//connect.facebook.net/en_US/fbds.js&apos;;
        ///                    var s = document.getElementsByTagName(&apos;script&apos;)[0];
        ///                    s.parentNode.insertB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MicksGarage {
            get {
                return ResourceManager.GetString("MicksGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-US&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;link rel=&quot;profile&quot; href=&quot;http://gmpg.org/xfn/11&quot;&gt;
        ///    &lt;link rel=&quot;pingback&quot; href=&quot;https://www.salesoptimize.com/xmlrpc.php&quot;&gt;
        ///
        ///    &lt;!--[if lt IE 9]&gt;
        ///        &lt;script src=&quot;//oss.maxcdn.com/html5shiv/3.7.2/html5shiv-printshiv.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;![endif]--&gt;
        ///    &lt;!-- if Favicon --&gt;
        ///    &lt;link rel=&quot;apple-touch-icon-precomposed&quot; sizes=&quot;152x152&quot; href=&quot; http [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SalesOptimize {
            get {
                return ResourceManager.GetString("SalesOptimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;!doctype html&gt;
        ///&lt;!--[if lt IE 7]&gt; &lt;html class=&quot;no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;    &lt;html class=&quot;no-js lt-ie10 lt-ie9 lt-ie8&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;    &lt;html class=&quot;no-js lt-ie10 lt-ie9&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 9]&gt;    &lt;html class=&quot;no-js lt-ie10&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html class=&quot;no-js&quot; lang=&quot;en&quot;&gt;
        /// &lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///
        ///    &lt;title&gt;Contact Us | Office location | Telephone, Email | Zarion Software&lt;/ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zarion {
            get {
                return ResourceManager.GetString("Zarion", resourceCulture);
            }
        }
    }
}
